language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - master

matrix:
  fast_finish: true
  allow_failures:
    - php: 'master'

before_script:
  - composer install --dev

branches:
  only:
    - master
    - travis
    - ci

script:
  - ./vendor/bin/phpunit --coverage-text

