language: php

before_script:
  - composer install --no-dev --verbose

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  allow_failures:
    - php: 7

branches:
  only:
    - master

script:
  - phpunit --coverage-text

